[tool.poetry]
name = "grotten"
version = "0.1.0"
description = "Text-based dungeon explorer written together with an 8-year-old"
authors = ["Stein Magnus Jodal <stein.magnus@jodal.no>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
black = "^19.10b0"
flake8 = "^3.7.9"
mypy = "^0.770"
pytest-watch = "^4.2.0"
pytest-mypy = "^0.6.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
target-version = ["py38"]
line-length = 80
